    event_inherited();
    myText[0] = "Well we are reaching the end now heh, I need to thank you before you leave.";
    mySpeaker = -1; 
	myName="Samus";
	myText[1]="Thanks to the friends of these 3, supporting them, pushing them to keep going,";
	myText[2]="even when others who sould support them don't, you're all part of this too and when the game ";
	myText[3]="is released expect to run into yourself on your playthrough,in some way or another.";
	myText[4]="Well, it's almost time for you to go, come back anytime, and hey uh that Jeremy";
	myText[5]="who was crying well uh, completely different one then the programmer by the way";
	myText[6]="no relation at all... haha...ha.heh....";