    event_inherited();
    myText[0] = " The next part of the Legend is hazy, for it is yet to occur"; 
    mySpeaker = -1; 
	myName="Ash";
	myText[1]="...However, there is one thing for certain, these 3 men will grow very close";
	myText[2]="The idea itself is quite beatiful isn't it?, the way things can bring people";
	myText[3]=" people together,people that never would have been friends before,heh..,hah...";
	myText[4]="I'm about to cry at my keyboard right now,but its not becasue I'm sad....";
	myText[5]="...The reason these men can carry on through these conditons is becasue they";
	myText[6]="All have something very special within them..";